version: '2'
services:
  cartographer-hokuyo3d:
    image: cartographer-hokuyo3d
    build: .
    environment:
      DISPLAY:
      QT_X11_NO_MITSHM: "1"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${HOME}/.slam_results/:/slam_results/"
    devices:
      - "/dev/dri:/dev/dri"
