version: '2'
services:
  roscore:
    image: ros:kinetic
    command: ["roscore"]
  cartographer-hokuyo3d:
    image: cartographer-hokuyo3d
    build: .
    environment:
      DISPLAY:
      QT_X11_NO_MITSHM: "1"
      ROS_MASTER_URI: "http://roscore:11311/"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    devices:
      - "/dev/dri:/dev/dri"
    depends_on:
      - roscore
